class_label: {
        1 : 'No entry',
        2 : 'No parking / waiting',
        3 : 'No turning',
        4 : 'Max Speed',
        5 : 'Other prohibition signs',
        6 : 'Warning',
        7 : 'Mandatory'
}

# train_label: '/content/drive/MyDrive/TrafficSign/data/za_traffic_2020/traffic_train/train.csv'
# test_label: '/content/drive/MyDrive/TrafficSign/data/za_traffic_2020/traffic_public_test/test.csv'
# val_label: '/content/drive/MyDrive/TrafficSign/data/za_traffic_2020/traffic_public_test/test.csv'
# train_imgs: '/content/drive/MyDrive/TrafficSign/data/za_traffic_2020/traffic_train/images/'
# val_imgs: '/content/drive/MyDrive/TrafficSign/data/za_traffic_2020/traffic_public_test/images/'
# test_imgs: '/content/drive/MyDrive/TrafficSign/data/za_traffic_2020/traffic_public_test/images/'
train_label: '/content/drive/MyDrive/TrafficSign/data/za_traffic_2020/traffic_train/train.csv'
test_label: '/content/drive/MyDrive/TrafficSign/data/za_traffic_2020/traffic_public_test/test.csv'
val_label: '/content/drive/MyDrive/TrafficSign/data/za_traffic_2020/traffic_public_test/test.csv'
train_imgs: '/content/'
val_imgs: '/content/'
test_imgs: '/content/'

loader_params: {'batch_size': 8,
          'shuffle': True,
          'pin_memory': True,
          'collate_fn': collate_fn,
          'num_workers': 4}
batch_size: 1
num_workers: 1
IMAGE_HEIGHT: 626
IMAGE_WIDTH: 1622

NUM_EPOCHS: 10